### PR TITLE
Support for Competitive Programming Gradle Plugin

### PR DESCRIPTION
**Pull request by saurabh73**
Closes:  #135

### CODE REVIEW

**Comment by jmerle** [comment]
I'm okay with the readme update but rather not add another port to that list. As can be read in the readme, could you please make your tool work with any of the already existing ports?

**Comment by saurabh73** [comment]
Sure I can use any existing port. Will update my PR and plugin code as well. 

Thanks 😊

**Comment by saurabh73** [comment]
@jmerle I've reverted the change to host file.

**Comment by jmerle** [comment]
Thanks!

**Pull request merged**
