### PR TITLE
remove NYTDOJ

### PR DESCRIPTION
**Pull request by gtn1024**
NYTDOJ do not use QDUOJ for some years.
Currently, remove it.

### CODE REVIEW

**Comment by touhidurrr** [comment]
even if it is not used, is there any reason as for why it needs to be removed? people can solve old questions also.

also, can you also add support for Hydro OJ in a separate pr? i think it would be better this way...

**Comment by touhidurrr** [comment]
also you editor seems to be adding or removing some whitespace characters maybe? some lines are shown as modified as git diff but i cannot see what changed. maybe this is an issue with the auto formatter that you use.

**Comment by gtn1024** [comment]
> even if it is not used, is there any reason as for why it needs to be removed? people can solve old questions also.
> 
> also, can you also add support for Hydro OJ in a separate pr? i think it would be better this way...

Yeah, I am currently maintaining the NYTDOJ. In years ago, we use our own OJ system to replace QDUOJ with the same domain/URL. So it does not work for a long time.

Now, we are migrating to Hydro. I may add it later. 

> also you editor seems to be adding or removing some whitespace characters maybe? some lines are shown as modified as git diff but i cannot see what changed. maybe this is an issue with the auto formatter that you use.

Yeah, my editor removed some whitespace characters in the end of some lines.

**Comment by gtn1024** [comment]
So, should I close this pr and open a new one later when we finally migrated to Hydro?

**Pull request closed without merging**
