### PR TITLE
Add support for Romanian online judges

### PR DESCRIPTION
**Pull request by overanalytcl**
This PR adds support for the following OJs:
- [Kilonova](https://kilonova.ro)
- [PBInfo](https://pbinfo.ro)
- [InfoArena](https://infoarena.ro) and [NerdArena](https://nerdarena.ro)

### CODE REVIEW

**Comment by overanalytcl** [comment]
Hello, @jmerle, have you had the time to look at this PR? Thank you.

**Comment by jmerle** [comment]
I've seen it, on first glance it looks good, but I haven't tested it yet. I'll get it reviewed, merged, and released before the end of this week.

**Comment by jmerle** [comment]
Thanks for the PR, it's really nice to see support for more parsers being added. I've made some changes described in the commit messages above, it's mostly refactoring to make the new parsers more consistent with existing parsers. I'll publish a new release containing your parsers tomorrow.

**Comment by overanalytcl** [comment]
I had NerdArena and InfoArena separated because at the time the layout was different enough for my approach to not work and the InfoArena parser to not be compatible with NerdArena. 

Thanks for all your work!

**Pull request merged**
