### PR TITLE
Add the support of HustOJ

### PR DESCRIPTION
**Pull request by zymooll**
This pr add the support of HustOJ,and it run correctly in my local environment.

### CODE REVIEW

**Comment by zymooll** [comment]
sorry i need to remove the change of MEADME.md

**Comment by zymooll** [comment]
sorry i need to solve some problems

**Comment by jmerle** [comment]
I'm not sure what the status this PR is, seeing how `getMatchPatterns()` still returns `['']` and how it first added an LSYOI parser and then switched to adding what seems like a HUSTOJ parser?

I'm not willing to add a generic HUSTOJ parser to this project because of HUSTOJ's customizability, but I don't have problems with parsers for specific online judges that happen to use HUSTOJ. For example, this project currently includes parsers for [BUCTOJ](https://github.com/jmerle/competitive-companion/blob/master/src/parsers/problem/BUCTOJProblemParser.ts) (#174) and [ZUFEOJ](https://github.com/jmerle/competitive-companion/blob/master/src/parsers/problem/ZUFEOJProblemParser.ts) (#297), both of which use HUSTOJ with its Syzoj theme.

**Comment by zymooll** [comment]
The LSYOI is our school’s internal OJ, and it based on the HustOJ.

At the first time, this parser is aim for my personal use.

And then, to create the PR, I change my original code.That is why I made so many commits.

Thanks for your reply. And if you want more informations of HustOJ. Here is the [link:](https://github.com/svn2github/hustoj)

**Comment by jmerle** [comment]
I'm still confused, so I'll put it like this:
- If the intent of this PR is to add a generic HUSTOJ parser to Competitive Companion I'm going to reject it.
- If the intent of this PR is to add an LSYOI parser to Competitive Companion you should revert it to [this](https://github.com/jmerle/competitive-companion/compare/master...7e8bc306b7ee3f2791220c4633e4a98bff475111) state, fix the import in `src/parsers/parsers.ts`, and make `getMatchPatterns()` return one or more proper match patterns instead of an empty string.

**Pull request closed without merging**
