### PR TITLE
Add LanqiaoProblemParser

### LINKED ISSUE #444: Hope to support LanQiao OJ(lanqiao.cn)
The LanQiao Cup is a student-oriented algorithmic competition that has emerged and gained popularity in China after 2020 and is open to students from elementary school to graduate school, and it also has its own OJ called **LanQiao OJ** and has weekly competitions, with OJ URL is **lanqiao.cn**, which I hope will be supported!

### PR DESCRIPTION
**Pull request by touhidurrr**
Resolves #444

### CODE REVIEW

**Comment by touhidurrr** [comment]
@Yerosius can you test the pr and see if this works for a variety of problems?

**Comment by touhidurrr** [comment]
I tested for these problems and it worked so far:
https://www.lanqiao.cn/problems/17162/learning/?contest_id=180
https://www.lanqiao.cn/problems/3584/learning/?page=1&first_category_id=1&asc=1&sort=difficulty

**Comment by Yerosius** [comment]
> 你能测试 PR 并看看它是否适用于各种问题吗？

Yes,it can work.

**Comment by Yerosius** [comment]
> I tested for these problems and it worked so far: https://www.lanqiao.cn/problems/17162/learning/?contest_id=180 https://www.lanqiao.cn/problems/3584/learning/?page=1&first_category_id=1&asc=1&sort=difficulty

@touhidurrr Can you work with contests? I looked for a URL for the contest:https://www.lanqiao.cn/oj-contest/newbie-9/

**Comment by Yerosius** [comment]
> > @touhidurrr Can you work with contests? I looked for a URL for the contest:https://www.lanqiao.cn/oj-contest/newbie-9/
> 
> The first link I mentioned was from a contest and it worked its problems. Can you try opening a problem from a contest and see if that works?

No, that's not what I was trying to express.What I'm trying to express is, is it possible to batch work all the problems in contset?

**Comment by touhidurrr** [comment]
Also, @jmerle, not sure why the checks have failed. I tried **lint:prettier** and **fix:prettier** locally and it shows no changes to commit.

**Comment by touhidurrr** [comment]
> @touhidurrr Can you work with contests? I looked for a URL for the contest:https://www.lanqiao.cn/oj-contest/newbie-9/

Oh I am not sure how contest parsers work yet. Similar to #443, maybe @jmerle needs to help here.

**Comment by Yerosius** [comment]
> > @touhidurrr Can you work with contests? I looked for a URL for the contest:https://www.lanqiao.cn/oj-contest/newbie-9/
> 
> Oh I am not sure how contest parsers work yet. Similar to #443, maybe @jmerle needs to help here.

Okay, I got it. Thanks for your contribution.

**Comment by jmerle** [comment]
For reference, this is a problem with multiple test cases: https://www.lanqiao.cn/problems/17160/learning/?contest_id=179

**Comment by touhidurrr** [comment]
@jmerle, using `pre > code` to select code blocks causes problems. For example, in this [problem](https://www.lanqiao.cn/problems/3584/learning/?page=1&first_category_id=1&asc=1&sort=difficulty), it selects a code block from problem statement.

**Comment by touhidurrr** [comment]
> For reference, this is a problem with multiple test cases: https://www.lanqiao.cn/problems/17160/learning/?contest_id=179

Nice catch. I thought since they have ids for sample input / output blocks, there will be only one of them. So, I was using them to avoid selecting blocks on problem statement. But now that I think about it, It is kind of dumb to think that there will only one I/O blocks per statement. Also, those ids were in Chinese probably because they generated not hardcoded.

**Comment by touhidurrr** [comment]
https://github.com/jmerle/competitive-companion/pull/445/commits/7354d446eb666605532aae4ed2c54d80843392ee, interesting solution indeed, but I would recommend using `pre > code.language-txt.plaintext` for now if it fixes the issue. Not perfect but better.

**Comment by jmerle** [comment]
Unfortunately not all test cases use `.language-txt.plaintext`, e.g. https://www.lanqiao.cn/problems/17159/learning/?contest_id=179 doesn't. This solution works until there is more than 1 no-test-case code block.

**Pull request merged**
